### ISSUE TITLE
Design files [open hardware plannings]

### ISSUE THREAD

**Issue by frankhelbert** [shamansystems/Cheap-FOCer#1]
I'm really interested in this project.
I'd like to start one by myself, but I use Eagle and the original VESC schematics and board were designed in Kicad. Lots of errors and dependencies not satisfied when I tried to modify the board.
There are any plans on releasing the schematics and board files? While I liked most modifications, I'd rather prefer the original MOSFETs, for example, so I'd like to change the schematics a little.
Really thanks and good work.

**Comment by nonsintetic** [comment]
Seconded, having the source files would help, especially since you seem to be moving to other projects. Would like to contribute.

**Comment by shamansystems** [comment]
Whoa hi there! Didn't know I had comments waiting for me so sorry about the delay here. So the project files are Altium and I don't intend to release them. What I do intend to do however is create the Cheap FOCer 2. It will be VESC 6 based, designed in kicad, have the project files available, and have a lot of design improvements. 

Stay up to date here!
https://forum.esk8.news/t/cheap-focer-vesc-compatible-4-12-redesign/1510
